---
title: "Homelab"
subtitle: "vpn"
logo: "logo.png"
header: true
footer: false
columns: "auto"
connectivityCheck: false

links:
  - name: "Pi-hole"
    icon: "fas fa-shield-alt"
    subtitle: "DNS + adblock .2"
    tag: "admin"
    url: "http://10.14.0.2/admin/"
    target: "_blank"
  - name: "Portainer"
    icon: "fab fa-docker"
    subtitle: "Manage containers .5:9443"
    tag: "admin"
    url: "https://10.14.0.5:9443/"
    target: "_blank"
  - name: "Chrome"
    icon: "fab fa-chrome"
    subtitle: "Web browser .3:3001"
    tag: "app"
    url: "https://10.14.0.3:3001/"
    target: "_blank"
  - name: "Terminal"
    icon: "fas fa-terminal"
    subtitle: "SSH web .6:3000"
    tag: "app"
    url: "https://10.14.0.6:3000/"
    target: "_blank"
  - name: "Status"
    icon: "fas fa-heartbeat"
    subtitle: "Monitors .9:3001"
    tag: "app"
    url: "http://10.14.0.9:3001/"
    target: "_blank"
  - name: "Backups"
    icon: "fas fa-save"
    subtitle: "Snapshots .10:9898"
    tag: "app"
    url: "http://10.14.0.10:9898/"
    target: "_blank"
  - name: "Files"
    icon: "fas fa-folder"
    subtitle: "File manager .11"
    tag: "app"
    url: "http://10.14.0.11/"
    target: "_blank"

services:
  - name: "Apps"
    icon: "fas fa-th"
    items:
      - name: "Pi-hole"
        subtitle: "DNS + adblock .2"
        url: "http://10.14.0.2/admin/"
        target: "_blank"
      - name: "Portainer"
        subtitle: "Manage containers .5:9443"
        url: "https://10.14.0.5:9443/"
        target: "_blank"
      - name: "Chrome"
        subtitle: "Web browser .3:3001"
        url: "https://10.14.0.3:3001/"
        target: "_blank"
      - name: "Terminal"
        subtitle: "SSH web .6:3000"
        url: "https://10.14.0.6:3000/"
        target: "_blank"
      - name: "Status"
        subtitle: "Monitors .9:3001"
        url: "http://10.14.0.9:3001/"
        target: "_blank"
      - name: "Backups"
        subtitle: "Snapshots .10:9898"
        url: "http://10.14.0.10:9898/"
        target: "_blank"
      - name: "Files"
        subtitle: "File manager .11"
        url: "http://10.14.0.11/"
        target: "_blank"
